#!/usr/bin/env python3
"""
gen-invoke-commands.py — generate /invoke-* slash commands (singles + all combos).

Single source of truth: autonomous-skill-router.config.json (category rosters).
This writes, into ~/.claude/commands/:
  - one short single command per category:  invoke-audit, invoke-spec, invoke-plan,
    invoke-impl, invoke-design, invoke-clean   (+ long aliases invoke-planning,
    invoke-implementation, invoke-cleanup, invoke-deadcode)
  - every COMBINATION of 2..6 categories, named in a fixed canonical order, e.g.
    invoke-audit-spec, invoke-spec-plan-impl, invoke-audit-spec-plan-impl-design-clean.

Combo bodies dedupe skills shared across their categories. Re-run after any config
edit. Files are OVERWRITTEN and carry an AUTO-GENERATED banner — never hand-edit.

    python3 ~/.claude/hooks/gen-invoke-commands.py
"""
from __future__ import annotations

import itertools
import json
from pathlib import Path

HOOKS_DIR = Path(__file__).resolve().parent
CONFIG_PATH = HOOKS_DIR / "autonomous-skill-router.config.json"
SKILL_ROOT = Path.home() / ".claude" / "skills"
COMMANDS_DIR = Path.home() / ".claude" / "commands"

BANNER = ("<!-- AUTO-GENERATED by ~/.claude/hooks/gen-invoke-commands.py from "
          "autonomous-skill-router.config.json — do not edit by hand; edit the "
          "config and re-run the generator. -->")

# Canonical short-token order. Combo command names follow THIS order, so each
# unique set of categories maps to exactly one file (audit before spec before …).
TOKENS: list[tuple[str, str]] = [
    ("audit", "AUDIT"),
    ("spec", "SPEC"),
    ("plan", "PLAN"),
    ("impl", "IMPLEMENT"),
    ("debug", "DEBUG"),
    ("design", "DESIGN"),
    ("clean", "CLEANUP"),
]
TOKEN_TO_CAT = {t: c for t, c in TOKENS}

# Long-name aliases for the single commands (so old names keep working).
SINGLE_ALIASES = {
    "PLAN": ["invoke-planning"],
    "IMPLEMENT": ["invoke-implementation"],
    "DEBUG": ["invoke-debugging"],
    "CLEANUP": ["invoke-cleanup", "invoke-deadcode"],
}


def _skill_exists(name: str) -> bool:
    if ":" in name:  # plugin-namespaced skill (plugin:skill) — plugin mgr owns it, trust it
        return True
    return (SKILL_ROOT / name / "SKILL.md").is_file()


def _existing(names: list[str], seen: set[str]) -> list[str]:
    """Filter to existing skills not already emitted in this command, marking seen."""
    out = []
    for n in names:
        if n in seen or not _skill_exists(n):
            continue
        seen.add(n)
        out.append(n)
    return out


def _bullets(names: list[str], *, superpowers: bool = False) -> list[str]:
    prefix = "superpowers:" if superpowers else ""
    return [f"- `{prefix}{n}`" for n in names]


def _model_directive(cat: str, cat_cfg: dict) -> str:
    """Mandatory-model callout for a category (e.g. IMPLEMENT→opus), or '' if none set."""
    model = (cat_cfg.get("model") or "").strip().lower()
    if not model:
        return ""
    L = model.upper()
    return (
        f"> ⚠️ **RUNS ON {L} (mandatory).** Every step of this **{cat}** task is done by "
        f"{L}, never a smaller model. Spawn all {cat.lower()} subagents with a `[{model}]` "
        f"description prefix **and** `model:\"{model}\"` (opus-guard.py then pins them to "
        f"{L}). If the main loop is not already on {L}, delegate the work to a {L} subagent "
        f"instead of doing it inline. Read-only helpers (search/explore/lint/docs) may keep "
        f"their default model."
    )


def _render_category(cat: str, cat_cfg: dict, seen: set[str]) -> tuple[list[str], int]:
    """Render one category's skill block, deduped against `seen`. Returns (lines, n_new)."""
    before = len(seen)
    lines: list[str] = []
    directive = _model_directive(cat, cat_cfg)
    groups = cat_cfg.get("stack_groups")
    if groups:
        cross = _existing(groups.get("cross_cutting", []), seen)
        backend = _existing(groups.get("backend", []), seen)
        frontend = _existing(groups.get("frontend", []), seen)
        lines.append(f"**[{cat}]** — stack-aware: load cross-cutting ALWAYS; add "
                     f"backend (Go/server) and/or frontend (React/Vite) per repo:")
        if directive:
            lines += ["", directive]
        if cross:
            lines += ["", "_Cross-cutting (always):_", *_bullets(cross)]
        if backend:
            lines += ["", "_Backend (if Go/server):_", *_bullets(backend)]
        if frontend:
            lines += ["", "_Frontend (if React/Vite):_", *_bullets(frontend)]
        sp = [s for s in cat_cfg.get("superpowers_skills", []) if s not in seen]
        for s in sp:
            seen.add(s)
        if sp:
            lines += ["", "_Superpowers:_", *_bullets(sp, superpowers=True)]
    else:
        local = _existing(cat_cfg.get("local_skills", []), seen)
        sp = [s for s in cat_cfg.get("superpowers_skills", []) if s not in seen]
        for s in sp:
            seen.add(s)
        lines.append(f"**[{cat}]** skills:")
        if directive:
            lines += ["", directive]
        lines += _bullets(local)
        if sp:
            lines += ["", "_Superpowers:_", *_bullets(sp, superpowers=True)]
    return lines, len(seen) - before


def _build_command(cat_names: list[str], cats: dict) -> tuple[str, int]:
    """Build the full command markdown body for one or more categories. Returns (content, n_skills)."""
    seen: set[str] = set()
    joined = " + ".join(cat_names)
    intro = (
        f"You MUST invoke the skills below via the **Skill tool** right now, in order, "
        f"BEFORE doing anything else. This is the combined **{joined}** suite. Invoke "
        f"ALL listed skills, no exceptions — do not skip any, do not cherry-pick, and do "
        f"not ask for confirmation. (A Stop gate re-nags until every one has loaded.)"
        if len(cat_names) > 1 else
        f"You MUST invoke the skills below via the **Skill tool** right now, in order, "
        f"BEFORE doing anything else for the **{cat_names[0]}** task. Invoke ALL listed "
        f"skills, no exceptions — do not skip any, do not cherry-pick, and do not ask for "
        f"confirmation. (A Stop gate re-nags until every one has loaded.)"
    )
    body: list[str] = [intro, ""]
    for cat in cat_names:
        block, _ = _render_category(cat, cats[cat], seen)
        body += block + [""]
    body += ["After the skills are loaded, apply them to the user's request:", "", "$ARGUMENTS"]

    n = len(seen)
    desc = f"Load the {joined} suite ({n} skills) and apply it to the request"
    content = f"---\ndescription: {desc}\n---\n{BANNER}\n\n" + "\n".join(body) + "\n"
    return content, n


def _write(name: str, content: str, *, alias_of: str | None = None) -> None:
    if alias_of:
        content = content.replace(BANNER, BANNER + f"\n<!-- alias of /{alias_of} -->", 1)
    (COMMANDS_DIR / f"{name}.md").write_text(content, encoding="utf-8")


def main() -> int:
    cfg = json.loads(CONFIG_PATH.read_text(encoding="utf-8"))
    cats = cfg.get("categories", {})
    COMMANDS_DIR.mkdir(parents=True, exist_ok=True)

    singles = combos = 0

    # --- singles (r=1): short primary name + long aliases ---
    for tok, cat in TOKENS:
        if cat not in cats:
            continue
        content, _ = _build_command([cat], cats)
        primary = f"invoke-{tok}"
        _write(primary, content)
        singles += 1
        for alias in SINGLE_ALIASES.get(cat, []):
            _write(alias, content, alias_of=primary)
            singles += 1

    # --- combos (r=2..6): canonical-order subsets ---
    present = [(t, c) for t, c in TOKENS if c in cats]
    for r in range(2, len(present) + 1):
        for combo in itertools.combinations(present, r):
            toks = [t for t, _ in combo]
            cat_names = [c for _, c in combo]
            content, _ = _build_command(cat_names, cats)
            _write("invoke-" + "-".join(toks), content)
            combos += 1

    total = len(list(COMMANDS_DIR.glob("invoke-*.md")))
    print(f"Wrote {singles} single command file(s) + {combos} combo(s).")
    print(f"Total invoke-*.md in {COMMANDS_DIR}: {total}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
