#!/usr/bin/env python3
"""
gen-invoke-skills.py — generate the /invoke skill family from config (v4: skills, not commands).

Output is deterministic (no timestamps), so `--check` is an exact comparison. Writes
skills/invoke/SKILL.md (+ references/rosters.md, the no-Agent-tool fallback), one
skills/invoke-<act>/SKILL.md per act (the main session dispatches the agent through the
Agent tool, so opus-guard routes it, into a run folder) and invoke-{session,status,update}.

Sources of truth (the act table lives ONLY in config):
  hooks/autonomous-skill-router.config.json
      categories.<CAT>.{act, order, mutates, agent, artifact, checkpoint, requires, local_skills, superpowers_skills}
      categories.IMPLEMENT.surface_routing (impl routing, the mixed order)
      orchestration.{closers_chain, closers_parallel, security_trigger_globs}
  hooks/model-policy.json  invoke_categories (per-act default model; default sonnet)
  hooks/lib/invoke_templates.py  the wording, and RUN_JSON (the one run.json schema)

    python3 ~/.claude/hooks/gen-invoke-skills.py           # write
    python3 ~/.claude/hooks/gen-invoke-skills.py --check   # exit 1 on drift: missing, stale, or unexpected invoke-* skills
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

HOOKS_DIR = Path(__file__).resolve().parent
CLAUDE_DIR = HOOKS_DIR.parent
CONFIG_PATH = HOOKS_DIR / "autonomous-skill-router.config.json"
MODEL_POLICY_PATH = HOOKS_DIR / "model-policy.json"
SKILLS_DIR = CLAUDE_DIR / "skills"

if str(HOOKS_DIR) not in sys.path:
    sys.path.insert(0, str(HOOKS_DIR))
from lib.invoke_templates import (  # noqa: E402
    ACT_NOTES, RUN_JSON, TEAMMATES, UTILITIES, delegator_body, impl_rule, invoke_body, rosters_body,
)

__all__ = ["RUN_JSON", "TEAMMATES", "UTILITIES"]

BANNER = ("<!-- AUTO-GENERATED by ~/.claude/hooks/gen-invoke-skills.py — do not edit by hand; "
          "edit hooks/autonomous-skill-router.config.json / hooks/model-policy.json and re-run "
          "(`--check` verifies). -->")


# ---------------------------------------------------------------------------
# config
# ---------------------------------------------------------------------------

def load_acts(cfg: dict) -> list[dict]:
    acts = []
    for cat, spec in cfg.get("categories", {}).items():
        if "act" not in spec:
            continue
        acts.append({
            "act": spec["act"], "cat": cat, "order": int(spec["order"]),
            "agent": spec["agent"], "artifact": spec["artifact"],
            "mutates": bool(spec.get("mutates")), "checkpoint": bool(spec.get("checkpoint")),
            "requires": spec.get("requires"),
            "local_skills": list(spec.get("local_skills") or []),
            "superpowers_skills": list(spec.get("superpowers_skills") or []),
        })
    acts.sort(key=lambda a: a["order"])
    names = [a["act"] for a in acts]
    if len(set(names)) != len(names):
        raise SystemExit(f"duplicate act tokens in config: {names}")
    if [a["order"] for a in acts] != list(range(1, len(acts) + 1)):
        raise SystemExit(f"act orders must be 1..N with no gaps: {[(a['act'], a['order']) for a in acts]}")
    return acts


def act_model(a: dict, policy: dict) -> str:
    return policy.get("invoke_categories", {}).get(a["cat"], policy.get("default", "sonnet"))


def surface_routing(cfg: dict) -> dict:
    r = (cfg.get("categories", {}).get("IMPLEMENT") or {}).get("surface_routing")
    if not isinstance(r, dict) or not isinstance(r.get("mixed"), list):
        raise SystemExit("categories.IMPLEMENT.surface_routing.mixed must be a list of agents")
    unknown = [a for a in r["mixed"] if a not in TEAMMATES]
    if unknown:
        raise SystemExit(f"surface_routing.mixed has agents with no teammate name: {unknown}")
    return r


def closers(cfg: dict, acts: list[dict]) -> tuple[list[str], list[str], str | None]:
    """(sequential pre-closers, parallel closers, final closer) — all agent names."""
    orch = cfg.get("orchestration", {})
    chain = list(orch.get("closers_chain") or [])
    par = list(orch.get("closers_parallel") or [])
    last = chain[-1] if chain and chain[-1] not in par else None
    pre = [c for c in chain if c not in par and c != last]
    return pre, par, last


# ---------------------------------------------------------------------------
# rendering
# ---------------------------------------------------------------------------

def _yaml_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _frontmatter(fields: dict) -> str:
    lines = ["---"]
    for k, v in fields.items():
        lines.append(f"{k}: {_yaml_str(v) if k in ('description', 'argument-hint') else v}")
    lines.append("---")
    return "\n".join(lines)


def _closer_line(agent: str, acts_by_agent: dict, policy: dict) -> str:
    a = acts_by_agent.get(agent)
    if a is None:
        return f"`{agent}` [sonnet]"
    return f"`{agent}` [{act_model(a, policy)}] (`{a['act']}`)"


def render_invoke(cfg: dict, policy: dict, acts: list[dict]) -> str:
    rows = "\n".join(
        f"| `{a['act']}` | {a['agent']} | `{a['artifact']}` | {act_model(a, policy)} "
        f"| {'yes' if a['mutates'] else 'no'} | {'yes' if a['checkpoint'] else 'no'} |"
        for a in acts)
    aba = {a["agent"]: a for a in acts}
    pre, par, last = closers(cfg, acts)
    steps = []
    for agent in pre:
        steps.append(f"{len(steps) + 1}. {_closer_line(agent, aba, policy)} — sequential first; it edits code.")
    if par:
        steps.append(f"{len(steps) + 1}. In ONE message (parallel): "
                     + ", ".join(_closer_line(a, aba, policy) for a in par) + ".")
    if last:
        steps.append(f"{len(steps) + 1}. {_closer_line(last, aba, policy)} — last, on the final tree.")
    impl = next((a for a in acts if a["act"] == "impl"), None)
    design = next((a for a in acts if a["act"] == "design"), None)

    description = ("Parametric orchestrator: `/invoke <acts...> [-- task]` runs one specialist subagent per act "
                   "in canonical order; artifacts in .claude/runs/<ts>-<slug>/; closers only after code-mutating acts.")
    assert len(description) <= 200, len(description)
    fm = _frontmatter({
        "name": "invoke",
        "description": description,
        "argument-hint": "<acts...> [--run <dir>] [-- task]",
        "user-invocable": "true",
    })
    body = invoke_body(
        order=" ".join(a["act"] for a in acts), rows=rows,
        impl=impl_rule(act_model(impl, policy) if impl else "sonnet", surface_routing(cfg)),
        design_model=act_model(design, policy) if design else "opus",
        checkpoints=", ".join(f"`{a['act']}`" for a in acts if a["checkpoint"]),
        globs=", ".join(f"`{g}`" for g in cfg.get("orchestration", {}).get("security_trigger_globs", [])),
        mutating=", ".join(f"`{a['act']}`" for a in acts if a["mutates"]),
        closer_block="\n".join(steps))
    return f"{fm}\n{BANNER}\n\n{body}"


def render_delegator(a: dict, policy: dict) -> str:
    description = (f"Run the {a['act'].upper()} act — dispatches {a['agent']} (default {act_model(a, policy)}; "
                   f"opus-guard routes) and writes `{a['artifact']}` into a run folder. "
                   f"Single-act form of `/invoke {a['act']} -- <task>`.")
    fm = _frontmatter({
        "name": f"invoke-{a['act']}",
        "description": description,
        "argument-hint": "[--run <dir>] [task]",
    })
    body = delegator_body(a["act"], a["agent"], a["artifact"], ACT_NOTES.get(a["act"], ""))
    return f"{fm}\n{BANNER}\n\n{body}"


def render_utility(name: str) -> str:
    u = UTILITIES[name]
    fields = {"name": name, "description": u["description"]}
    fields.update(u["extra"])
    return f"""{_frontmatter(fields)}
{BANNER}

{u['body']}
"""


# ---------------------------------------------------------------------------
# emit / check
# ---------------------------------------------------------------------------

def render_all(cfg: dict, policy: dict) -> dict[Path, str]:
    acts = load_acts(cfg)
    out = {
        SKILLS_DIR / "invoke" / "SKILL.md": render_invoke(cfg, policy, acts),
        SKILLS_DIR / "invoke" / "references" / "rosters.md": rosters_body(acts, BANNER),
    }
    for a in acts:
        out[SKILLS_DIR / f"invoke-{a['act']}" / "SKILL.md"] = render_delegator(a, policy)
    for name in UTILITIES:
        out[SKILLS_DIR / name / "SKILL.md"] = render_utility(name)
    return out


def _rel(p: Path) -> str:
    try:
        return str(p.relative_to(CLAUDE_DIR))
    except ValueError:
        return str(p)


def unexpected_dirs(expected: dict[Path, str]) -> list[Path]:
    want = {p.parent if p.name == "SKILL.md" else p.parent.parent for p in expected}
    have = {p for p in SKILLS_DIR.glob("invoke*") if p.is_dir()}
    return sorted(have - want)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="exit 1 if the skills on disk differ from the render")
    args = ap.parse_args()

    cfg = json.loads(CONFIG_PATH.read_text(encoding="utf-8"))
    policy = json.loads(MODEL_POLICY_PATH.read_text(encoding="utf-8")) if MODEL_POLICY_PATH.exists() else {}
    rendered = render_all(cfg, policy)
    stale = unexpected_dirs(rendered)

    if args.check:
        drift = []
        for path, content in rendered.items():
            if not path.is_file():
                drift.append(f"missing  {_rel(path)}")
            elif path.read_text(encoding="utf-8") != content:
                drift.append(f"stale    {_rel(path)}")
        drift += [f"unexpected {_rel(p)}/ (not generated from config)" for p in stale]
        if drift:
            print("gen-invoke-skills --check: DRIFT\n  " + "\n  ".join(drift))
            print("run `python3 ~/.claude/hooks/gen-invoke-skills.py` and delete unexpected dirs.")
            return 1
        print(f"gen-invoke-skills --check: OK ({len(rendered)} files in sync)")
        return 0

    for path, content in rendered.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")
    print(f"gen-invoke-skills: wrote {len(rendered)} files under {_rel(SKILLS_DIR)}/")
    for p in stale:
        print(f"  warning: unexpected {_rel(p)}/ is not generated from config - delete it")
    return 0


if __name__ == "__main__":
    sys.exit(main())
