#!/usr/bin/env python3
"""gen-agent-skill-blocks.py — sync agent .md skill-loading blocks from config.

The implementor/integrator agents carry a "Skill loading" list between
<!-- skills:auto:start --> / <!-- skills:auto:end --> markers. This generator
rewrites that block from the single source of truth so agent checklists can
never drift from routing config again (root cause #5 of the 2026-07-18 audit):

  agent -> skills source
  ---------------------------------------------------------------
  backend-implementor-specialist   BACKEND_SKILLS (fullstack-skills-reminder.py)
  frontend-implementor-specialist  FRONTEND_SKILLS (same)
  implementation-engineer          cross-cutting core (skill_router.config.json
                                   cross_cutting: always + first_write_only +
                                   implementation + verification)
  audit-specialist / spec-architect / planning-director / debug-detective /
  deadcode-reaper / docs-sync-agent / qa-verifier / santa-reviewer /
  security-sentinel / test-author / refactor-specialist
                                   categories.<CAT>.local_skills
                                   (autonomous-skill-router.config.json)

Alias-collapse map applied everywhere so agents load canonicals, not stubs.
Agents without markers are skipped (never rewritten). Idempotent; --check
exits 1 if any block is stale (used by installer verify).
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

HOOKS = Path(__file__).resolve().parent
AGENTS = HOOKS.parent / "agents"
START, END = "<!-- skills:auto:start -->", "<!-- skills:auto:end -->"

ALIAS = {
    "diagnose": "debug-investigation",
    "debugging-and-error-recovery": "debug-investigation",
    "api-and-interface-design": "api-contract-standards",
    "tdd": "test-driven-development",
    "forensic-change-coupling": "tech-debt-audit",
    "forensic-complexity-trends": "tech-debt-audit",
    "forensic-debt-quantification": "tech-debt-audit",
    "forensic-hotspot-finder": "tech-debt-audit",
    "improve-codebase-architecture": "tech-debt-audit",
    "security-and-hardening": "owasp-security",
    "domain-scaffold-patterns": "scaffold-standards",
    "frontend-api-standards": "frontend-response-handling",
    "browser-testing-with-devtools": "webapp-testing",
    "incremental-implementation": "code-execution-standard",
    "plan-exec-stack-guide": "workflow-orchestrator",
    "project-structure-map": "codebase-intel-first",
    "zoom-out": "codebase-intel-first",
    "jcodemunch-token-saver": "codebase-intel-first",
    "codebase-start-point-guide": "codebase-intel-first",
    "iterative-retrieval": "codebase-intel-first",
    "documentation-and-adrs": "update-docs",
}

CATEGORY_AGENTS = {
    "audit-specialist": "AUDIT", "spec-architect": "SPEC",
    "planning-director": "PLAN", "debug-detective": "DEBUG",
    "deadcode-reaper": "CLEANUP", "docs-sync-agent": "DOCS",
    "qa-verifier": "VERIFY", "santa-reviewer": "REVIEW",
    "security-sentinel": "SECURITY", "test-author": "TEST",
    "refactor-specialist": "REFACTOR",
}


def _load(p: Path) -> dict:
    try:
        return json.loads(p.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}


def _collapse(skills: list[str]) -> list[str]:
    out: list[str] = []
    for s in skills:
        c = ALIAS.get(s, s)
        if c not in out:
            out.append(c)
    return out


def _fsr_lists() -> tuple[list[str], list[str]]:
    """FRONTEND_SKILLS / BACKEND_SKILLS parsed from fullstack-skills-reminder.py
    without importing it (it has hook side effects)."""
    src = (HOOKS / "fullstack-skills-reminder.py").read_text(encoding="utf-8")

    def grab(name: str) -> list[str]:
        m = re.search(rf"{name}\s*(?::[^=]*)?=\s*\[(.*?)\]", src, re.S)
        return re.findall(r'"([\w:-]+)"', m.group(1)) if m else []

    return grab("FRONTEND_SKILLS"), grab("BACKEND_SKILLS")


def _agent_skills() -> dict[str, list[str]]:
    fe, be = _fsr_lists()
    cats = _load(HOOKS / "autonomous-skill-router.config.json").get("categories", {})
    cc = _load(HOOKS / "skill_router.config.json").get("cross_cutting", {})
    core = []
    for grp in ("always", "first_write_only", "implementation", "verification"):
        core += cc.get(grp, [])
    out = {
        "backend-implementor-specialist": _collapse(be),
        "frontend-implementor-specialist": _collapse(fe),
        "implementation-engineer": _collapse(core),
    }
    for agent, cat in CATEGORY_AGENTS.items():
        ls = (cats.get(cat) or {}).get("local_skills") or []
        if ls:
            out[agent] = _collapse(ls)
    return out


def _render(skills: list[str]) -> str:
    lines = "\n".join(f"- {s}" for s in skills)
    return (f"{START}\n<!-- generated by hooks/gen-agent-skill-blocks.py — do not hand-edit;"
            f" edit the routing config and re-run -->\n{lines}\n{END}")


def main(argv: list[str]) -> int:
    check = "--check" in argv
    stale, written, skipped = [], [], []
    for agent, skills in _agent_skills().items():
        p = AGENTS / f"{agent}.md"
        if not p.is_file():
            skipped.append(agent)
            continue
        t = p.read_text(encoding="utf-8")
        if START not in t or END not in t:
            skipped.append(agent)
            continue
        block = _render(skills)
        new = re.sub(re.escape(START) + r".*?" + re.escape(END), lambda _: block, t, flags=re.S)
        if new != t:
            if check:
                stale.append(agent)
            else:
                p.write_text(new, encoding="utf-8")
                written.append(agent)
    if check:
        print(f"agent-skill-blocks: {'STALE: ' + ', '.join(stale) if stale else 'all in sync'}"
              f" ({len(skipped)} without markers skipped)")
        return 1 if stale else 0
    print(f"agent-skill-blocks: rewrote {len(written)} ({', '.join(written) or 'none'}); "
          f"{len(skipped)} without markers skipped")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
