#!/usr/bin/env python3
"""
gen-invoke-commands.py — generate /invoke slash commands (v3: PARAMETRIC collapse).

Default `surface: "parametric"` emits exactly 20 files:
  - invoke.md                     parametric `/invoke <acts...> [-- task]`
  - 10 single-act delegators      invoke-{audit,spec,plan,impl,debug,design,clean,
                                  docs,verify,security}.md -> `/invoke <act> -- $ARGS`
  - invoke-fullstack.md           -> `/invoke spec plan impl`
  - 5 muscle-memory aliases       invoke-{cleanup,deadcode,debugging,implementation,
                                  planning}.md -> their single-act delegator
  - 3 utilities                   invoke-{session,status,update}.md

The 120 multi-act combo files are RETIRED (atticked by scripts/attic.py; names kept
in trigger-floor.json's `commands` section + the router `invoke_compat` translator).

`--emit-combos` regenerates all 120 combos from config (instant rollback; default off).

Sources of truth:
  - hooks/autonomous-skill-router.config.json  (categories.* rosters + orchestration)
  - hooks/model-policy.json  invoke_categories  (per-act model pin; IMPLEMENT=opus)

    python3 ~/.claude/hooks/gen-invoke-commands.py            # 20 files
    python3 ~/.claude/hooks/gen-invoke-commands.py --emit-combos
"""
from __future__ import annotations

import argparse
import itertools
import json
from pathlib import Path

HOOKS_DIR = Path(__file__).resolve().parent
CONFIG_PATH = HOOKS_DIR / "autonomous-skill-router.config.json"
MODEL_POLICY_PATH = HOOKS_DIR / "model-policy.json"
COMMANDS_DIR = Path.home() / ".claude" / "commands"

BANNER = ("<!-- AUTO-GENERATED by ~/.claude/hooks/gen-invoke-commands.py "
          "(parametric v3) — do not edit by hand; edit the config/model-policy and "
          "re-run the generator. -->")

# act token -> (CATEGORY key in config or None, agent, artifact, one-line role)
ACTS: dict[str, dict] = {
    "audit":   {"cat": "AUDIT",     "agent": "audit-specialist",        "artifact": "AUDIT-{date}.md",   "role": "tech-debt / forensic / architecture audit"},
    "spec":    {"cat": "SPEC",      "agent": "spec-architect",          "artifact": "SPEC-{slug}.md",    "role": "build-ready spec + contracts"},
    "plan":    {"cat": "PLAN",      "agent": "planning-director",       "artifact": "plan-{date}-{slug}.md", "role": "phased execution plan"},
    "test":    {"cat": "TEST",      "agent": "test-author",             "artifact": "TEST-REPORT.md",    "role": "author failing tests first (TDD red)"},
    "impl":    {"cat": "IMPLEMENT", "agent": "implementation-engineer", "artifact": "IMPL-REPORT.md",    "role": "implement the plan (RUNS ON OPUS)"},
    "refactor":{"cat": "REFACTOR",  "agent": "refactor-specialist",     "artifact": "REFACTOR-REPORT.md","role": "behavior-preserving refactor (test-guarded)"},
    "debug":   {"cat": "DEBUG",     "agent": "debug-detective",         "artifact": "ROOTCAUSE.md",      "role": "root-cause an unknown failure"},
    "design":  {"cat": "DESIGN",    "agent": "frontend-uiux-designer",  "artifact": "DESIGN-REPORT.md",  "role": "UI/UX design + polish (opus)"},
    "clean":   {"cat": "CLEANUP",   "agent": "deadcode-reaper",         "artifact": "REAP-REPORT.md",    "role": "dead-code reap (code-mutating)"},
    "review":  {"cat": "REVIEW",    "agent": "santa-reviewer",          "artifact": "SANTA-REVIEW.md",   "role": "Santa Method adversarial review (opus)"},
    "docs":    {"cat": None,        "agent": "docs-sync-agent",         "artifact": "DOCS-SYNC-REPORT.md","role": "sync docs to the change"},
    "verify":  {"cat": None,        "agent": "qa-verifier",             "artifact": "VERIFY-REPORT.md",  "role": "verify behavior end-to-end"},
    "security":{"cat": "SECURITY",  "agent": "security-sentinel",       "artifact": "SECURITY-REPORT.md","role": "security review / hardening"},
}
CANON_ORDER = list(ACTS.keys())

# muscle-memory aliases -> their single-act delegator
MUSCLE_ALIASES = {
    "invoke-cleanup": "clean", "invoke-deadcode": "clean", "invoke-debugging": "debug",
    "invoke-implementation": "impl", "invoke-planning": "plan",
}


def load_config() -> dict:
    return json.loads(CONFIG_PATH.read_text())


def act_model(act: str, model_policy: dict) -> str:
    cat = ACTS[act]["cat"]
    inv = model_policy.get("invoke_categories", {})
    if cat and cat in inv:
        return inv[cat]
    if act in ("design", "impl"):  # UI/impl agents opus-pinned by opus-guard regardless
        return "opus"
    return "sonnet"


def roster_for(act: str, cfg: dict) -> list[str]:
    cat = ACTS[act]["cat"]
    if not cat or cat not in cfg.get("categories", {}):
        return []
    skills = list(cfg["categories"][cat].get("local_skills", []))
    if act == "design" and "higgsfield-generate" not in skills:
        skills.append("higgsfield-generate")  # Higgsfield asset mandate
    return skills


def render_parametric(cfg: dict, model_policy: dict) -> str:
    rows = "\n".join(
        f"| `{a}` | {ACTS[a]['agent']} | `{ACTS[a]['artifact']}` | {act_model(a, model_policy)} "
        f"| {ACTS[a]['role']} |" for a in CANON_ORDER)
    fb = []
    for a in CANON_ORDER:
        skills = roster_for(a, cfg)
        if skills:
            lst = "\n".join(f"  - `{s}`" for s in skills)
            fb.append(f"<details><summary><code>{a}</code> fallback roster</summary>\n\n{lst}\n</details>")
    fallback_block = "\n".join(fb)
    closers = ", ".join(cfg.get("orchestration", {}).get("closers_chain", []))
    return f"""---
description: Parametric orchestrator — `/invoke <acts...> [-- task]` runs one specialist per act (intel once, cumulative artifacts, closers once). Acts {' '.join(CANON_ORDER)}.
---
{BANNER}

# /invoke &lt;acts...&gt; [-- task]

Run any combination of acts in ONE flow, e.g. `/invoke audit plan impl -- add rate limiting`.
Acts always run in this canonical order regardless of how they are typed:

| act | specialist agent | artifact | model | role |
|-----|------------------|----------|-------|------|
{rows}

An unknown token is reported ("valid acts: …") and the flow proceeds with the recognized acts.

## ACT A — INTEL (once, yourself, no dispatch)

1. jcodemunch `plan_turn` (query = task) + `assemble_task_context` on the impacted area.
2. graphify `graph_stats` + `query_graph` (freshness — rebuild only if a guard said STALE).
3. Read `CODEX.md` + the repo root→target `CLAUDE.md` (dox tree).
4. Produce the **BRIEF** (task, surfaces FE/BE/infra, impacted layers, contracts at risk, paths).

Every specialist below receives this BRIEF **plus the cumulative artifact set** from acts already
completed — later acts start warm and never re-derive earlier context.

## ACT B — DISPATCH (one specialist per requested act, canonical order)

For each requested act, spawn its agent (Agent tool, `subagent_type` = the agent above) with the
description prefix `[<model>] ` from the table and `model:"<model>"`, passing the BRIEF + **every
prior artifact**. Wait for the act's artifact before the next act.

- **`impl` RUNS ON OPUS (mandatory)** — `implementation-engineer` gets `[opus]` + `model:"opus"`
  (model-policy `invoke_categories.IMPLEMENT`). When PLAN already ran, its plan artifact is the
  implementation input and the `requires: plan` note is satisfied — do not re-ask.
- **`design`** dispatches `frontend-uiux-designer` (opus); assets come from Higgsfield
  (`higgsfield-generate`) per the frontend asset mandate.
- **`clean`** is code-mutating — treat REAP edits as real changes (audit + verify after).

## ACT C — CLOSERS (once, after all acts)

Run the closers chain on the cumulative result: {closers}.

## FALLBACK — legacy inline rosters (dispatch unavailable)

If the Agent tool is unavailable, invoke each act's skills yourself via the Skill tool, in order,
executing every act sequentially. Never silently drop an act.

{fallback_block}
"""


def render_delegator(act: str) -> str:
    return f"""---
description: Delegator — run the {act.upper()} act. Equivalent to `/invoke {act} -- $ARGS`.
---
{BANNER}

Run `/invoke {act} -- $ARGS` — single-act dispatch of the parametric orchestrator (see `invoke.md`).
"""


def render_alias(name: str, act: str) -> str:
    return f"""---
description: Alias (muscle memory) for the {act.upper()} act — same as `/invoke {act}`.
---
{BANNER}

Run `/invoke {act} -- $ARGS`. (Muscle-memory alias -> `invoke-{act}`.)
"""


def render_fullstack() -> str:
    return f"""---
description: Full-stack flow — spec then plan then implement. Equivalent to `/invoke spec plan impl`.
---
{BANNER}

Run `/invoke spec plan impl -- $ARGS` (SPEC -> PLAN -> IMPLEMENT with cumulative artifacts; the
implement act RUNS ON OPUS).
"""


UTILITIES = {
    "invoke-session": ("Session init — index/graph freshness, memory + CODEX load, repo "
                       "orientation, dox check -> ready report.",
                       "Run the session-init flow: verify jcodemunch + graphify freshness "
                       "(rebuild only if STALE), load Memory MCP + CODEX.md, orient (get_repo_map), "
                       "confirm the dox root, print a READY report."),
    "invoke-status": ("Where am I? — last artifacts, unfinished chains, gate states, suggested "
                      "resume command.",
                      "Report current state: newest `*-REPORT.md` / plan / spec artifacts, any "
                      "unfinished `/invoke` chain, gate states, and the suggested resume command."),
    "invoke-update": ("Upstream skill sync — read hooks/skills-provenance.json, run per-family "
                      "update commands, re-sync gstack pointers, doctor R10.",
                      "For each entry in `hooks/skills-provenance.json`, run its family "
                      "`updateCommand` (gstack-upgrade / npx skills update / gsd-update / re-vendor "
                      "/ .git-upstream pull); then `python3 scripts/sync-gstack-pointers.py` and "
                      "`python3 scripts/build_provenance.py --check` (R10). Report drift."),
}


def render_utility(name: str) -> str:
    desc, body = UTILITIES[name]
    return f"""---
description: {desc}
---
{BANNER}

{body}
"""


def emit_parametric(cfg: dict, model_policy: dict) -> list[str]:
    COMMANDS_DIR.mkdir(parents=True, exist_ok=True)
    written = []

    def write(name: str, content: str):
        (COMMANDS_DIR / f"{name}.md").write_text(content, encoding="utf-8")
        written.append(name)

    write("invoke", render_parametric(cfg, model_policy))
    for act in ACTS:
        write(f"invoke-{act}", render_delegator(act))
    write("invoke-fullstack", render_fullstack())
    for alias, act in MUSCLE_ALIASES.items():
        write(alias, render_alias(alias, act))
    for name in UTILITIES:
        write(name, render_utility(name))
    return written


def emit_combos(cfg: dict, model_policy: dict) -> list[str]:
    """Rollback path: regenerate all 120 multi-act combo delegators."""
    COMMANDS_DIR.mkdir(parents=True, exist_ok=True)
    written = []
    tokens = ["audit", "spec", "plan", "impl", "debug", "design", "clean"]
    for r in range(2, len(tokens) + 1):
        for combo in itertools.combinations(tokens, r):
            name = "invoke-" + "-".join(combo)
            acts = " ".join(combo)
            (COMMANDS_DIR / f"{name}.md").write_text(
                f"---\ndescription: Combo delegator -> `/invoke {acts}`.\n---\n{BANNER}\n\n"
                f"Run `/invoke {acts} -- $ARGS`.\n", encoding="utf-8")
            written.append(name)
    return written


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--emit-combos", action="store_true",
                    help="ALSO regenerate the 120 combo files (rollback path)")
    args = ap.parse_args()
    cfg = load_config()
    model_policy = json.loads(MODEL_POLICY_PATH.read_text()) if MODEL_POLICY_PATH.exists() else {}
    written = emit_parametric(cfg, model_policy)
    print(f"parametric surface: wrote {len(written)} files")
    if args.emit_combos:
        combos = emit_combos(cfg, model_policy)
        print(f"--emit-combos: wrote {len(combos)} combo files (rollback)")
    return 0


if __name__ == "__main__":
    main()
