#!/usr/bin/env python3
"""
gen-invoke-skills.py — generate the /invoke skill family from config (v4: skills, not commands).

Output is deterministic (no timestamps), so `--check` is an exact comparison.

  skills/invoke/SKILL.md                         parametric `/invoke <acts...> [-- task]`
  skills/invoke/references/rosters.md            fallback skill rosters (read only when the Agent tool is unavailable)
  skills/invoke-<act>/SKILL.md                   one forked single-act delegator per act (context: fork + agent:)
  skills/invoke-{session,status,update}/SKILL.md utilities

Sources of truth (the act table lives ONLY in config):
  hooks/autonomous-skill-router.config.json
      categories.<CAT>.{act, order, mutates, agent, artifact, checkpoint, requires, local_skills, superpowers_skills}
      orchestration.{closers_chain, closers_parallel, security_trigger_globs}
  hooks/model-policy.json  invoke_categories (per-act model; default sonnet)

    python3 ~/.claude/hooks/gen-invoke-skills.py           # write
    python3 ~/.claude/hooks/gen-invoke-skills.py --check   # exit 1 on drift: missing, stale, or unexpected invoke-* skills
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

HOOKS_DIR = Path(__file__).resolve().parent
CLAUDE_DIR = HOOKS_DIR.parent
CONFIG_PATH = HOOKS_DIR / "autonomous-skill-router.config.json"
MODEL_POLICY_PATH = HOOKS_DIR / "model-policy.json"
SKILLS_DIR = CLAUDE_DIR / "skills"

BANNER = ("<!-- AUTO-GENERATED by ~/.claude/hooks/gen-invoke-skills.py — do not edit by hand; "
          "edit hooks/autonomous-skill-router.config.json / hooks/model-policy.json and re-run "
          "(`--check` verifies). -->")

RUN_MKDIR = ".claude/runs/$(date -u +%Y%m%dT%H%M)-<slug>/"

# Prose only — nothing routing-relevant lives here.
ACT_NOTES = {
    "impl": ("This delegator always forks into `implementation-engineer` (general/infra). For frontend- or "
             "backend-specific work prefer `/invoke impl -- <task>`, which surface-routes to the FE/BE "
             "specialists. A plan artifact in the run folder is your input; without one, write a mini-plan "
             "first, then implement task-by-task with TDD."),
    "design": ("Every raster/video/3D/audio asset comes from Higgsfield (`higgsfield-generate`); placeholder "
               "boxes, stock URLs and emoji icons are a hard fail."),
    "review": ("Review the target above, or this session's diff when it is empty. Read the ACTUAL changed "
               "files, run BREAKER + SIMPLIFIER + VERIFIER, and return only CONFIRMED findings "
               "(`file:line` + minimal fix) plus a PASS / CHANGES REQUESTED verdict. Never edit code."),
    "debug": ("Demonstrate the root cause with evidence BEFORE proposing a fix; include the killed "
              "hypotheses so nobody re-treads them."),
    "clean": ("Remove only what THIS session's diff orphaned (verify each with `check_delete_safe`); "
              "report pre-existing dead code without touching it."),
}

UTILITIES = {
    "invoke-session": {
        "description": ("Session init — index/graph freshness, memory + CODEX load, repo orientation, "
                        "dox check -> ready report."),
        "extra": {},
        "body": ("Run the session-init flow: verify jcodemunch + graphify freshness (rebuild only if STALE), "
                 "load Memory MCP + CODEX.md, orient (get_repo_map), confirm the dox root, print a READY "
                 "report."),
    },
    "invoke-status": {
        "description": ("Where am I? — newest .claude/runs/ run.json: acts done/pending, artifacts "
                        "present/missing, gate state, suggested resume command."),
        "extra": {"allowed-tools": "Read, Glob, Bash(ls:*), Bash(cat:*)"},
        "body": (
            "Report where the current `/invoke` work stands. Read-only.\n\n"
            "1. Newest run: `ls -dt .claude/runs/*/ | head -1`. Read its `run.json` "
            "(`task`, `acts`, `done`, `models`, `expected_artifacts`).\n"
            "2. Pending acts = `acts` minus `done`. For every entry in `expected_artifacts` say whether the "
            "file exists; missing ones are the blockers.\n"
            "3. Verdict lines, when the reports exist in the run folder: `SANTA-REVIEW.md` "
            "(PASS / CHANGES REQUESTED), `SECURITY-REPORT.md` (PASS / BLOCK), `VERIFY-REPORT.md` (PASS / FAIL).\n"
            "4. Gate state: `~/.claude/hooks/.telemetry/*.suite-gate.json` for this conversation, if present.\n"
            "5. Print: run path · done / pending · artifacts present / missing · verdicts · suggested resume "
            "`/invoke <pending acts> -- <task>`.\n\n"
            "No `.claude/runs/` folder → say so and suggest `/invoke <acts> -- <task>`."
        ),
    },
    "invoke-update": {
        "description": ("Upstream skill sync — check vendored third-party skills against their pinned "
                        "sources, update on confirmation, then re-verify provenance (R10)."),
        "extra": {"disable-model-invocation": "true"},
        "body": (
            "Sync vendored third-party skills with their pinned upstreams (`hooks/skills-sources.json`).\n\n"
            "1. `python3 ~/.claude/scripts/vendor_skill.py --all --check` — report drift per skill "
            "(exit 1 = drift).\n"
            "2. Only after the user confirms: `python3 ~/.claude/scripts/vendor_skill.py --all`.\n"
            "3. `python3 ~/.claude/scripts/build_provenance.py --check` — report the R10 result.\n\n"
            "Never run step 2 without an explicit yes — it touches the network and git."
        ),
    },
}


# ---------------------------------------------------------------------------
# config
# ---------------------------------------------------------------------------

def load_acts(cfg: dict) -> list[dict]:
    acts = []
    for cat, spec in cfg.get("categories", {}).items():
        if "act" not in spec:
            continue
        acts.append({
            "act": spec["act"], "cat": cat, "order": int(spec["order"]),
            "agent": spec["agent"], "artifact": spec["artifact"],
            "mutates": bool(spec.get("mutates")), "checkpoint": bool(spec.get("checkpoint")),
            "requires": spec.get("requires"),
            "local_skills": list(spec.get("local_skills") or []),
            "superpowers_skills": list(spec.get("superpowers_skills") or []),
        })
    acts.sort(key=lambda a: a["order"])
    names = [a["act"] for a in acts]
    if len(set(names)) != len(names):
        raise SystemExit(f"duplicate act tokens in config: {names}")
    if [a["order"] for a in acts] != list(range(1, len(acts) + 1)):
        raise SystemExit(f"act orders must be 1..N with no gaps: {[(a['act'], a['order']) for a in acts]}")
    return acts


def act_model(a: dict, policy: dict) -> str:
    return policy.get("invoke_categories", {}).get(a["cat"], policy.get("default", "sonnet"))


def closers(cfg: dict, acts: list[dict]) -> tuple[list[str], list[str], str | None]:
    """(sequential pre-closers, parallel closers, final closer) — all agent names."""
    orch = cfg.get("orchestration", {})
    chain = list(orch.get("closers_chain") or [])
    par = list(orch.get("closers_parallel") or [])
    last = chain[-1] if chain and chain[-1] not in par else None
    pre = [c for c in chain if c not in par and c != last]
    return pre, par, last


def by_agent(acts: list[dict]) -> dict:
    return {a["agent"]: a for a in acts}


# ---------------------------------------------------------------------------
# rendering
# ---------------------------------------------------------------------------

def _yaml_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _frontmatter(fields: dict) -> str:
    lines = ["---"]
    for k, v in fields.items():
        lines.append(f"{k}: {_yaml_str(v) if k in ('description', 'argument-hint') else v}")
    lines.append("---")
    return "\n".join(lines)


def _closer_line(agent: str, acts_by_agent: dict, policy: dict) -> str:
    a = acts_by_agent.get(agent)
    if a is None:
        return f"`{agent}` [sonnet]"
    return f"`{agent}` [{act_model(a, policy)}] (`{a['act']}`)"


def render_invoke(cfg: dict, policy: dict, acts: list[dict]) -> str:
    order = " ".join(a["act"] for a in acts)
    rows = "\n".join(
        f"| `{a['act']}` | {a['agent']} | `{a['artifact']}` | {act_model(a, policy)} "
        f"| {'yes' if a['mutates'] else 'no'} | {'yes' if a['checkpoint'] else 'no'} |"
        for a in acts)
    globs = ", ".join(f"`{g}`" for g in cfg.get("orchestration", {}).get("security_trigger_globs", []))
    checkpoints = ", ".join(f"`{a['act']}`" for a in acts if a["checkpoint"])
    mutating = ", ".join(f"`{a['act']}`" for a in acts if a["mutates"])
    aba = by_agent(acts)
    pre, par, last = closers(cfg, acts)
    steps = []
    for agent in pre:
        steps.append(f"{len(steps) + 1}. {_closer_line(agent, aba, policy)} — sequential first; it edits code.")
    if par:
        steps.append(f"{len(steps) + 1}. In ONE message (parallel): "
                     + ", ".join(_closer_line(a, aba, policy) for a in par) + ".")
    if last:
        steps.append(f"{len(steps) + 1}. {_closer_line(last, aba, policy)} — last, on the final tree.")
    closer_block = "\n".join(steps)
    impl = next((a for a in acts if a["act"] == "impl"), None)
    impl_model = act_model(impl, policy) if impl else "opus"
    design = next((a for a in acts if a["act"] == "design"), None)
    design_model = act_model(design, policy) if design else "opus"

    description = (f"Parametric orchestrator: `/invoke <acts...> [-- task]` runs one specialist subagent per act "
                   f"in canonical order; artifacts in .claude/runs/<ts>-<slug>/; closers only after code-mutating acts.")
    assert len(description) <= 200, len(description)
    fm = _frontmatter({
        "name": "invoke",
        "description": description,
        "argument-hint": "<acts...> [-- task]",
        "user-invocable": "true",
    })
    return f"""{fm}
{BANNER}

# /invoke $ARGUMENTS

## 1. Parse `$ARGUMENTS`

- Tokens before ` -- ` are acts; everything after is the TASK (empty → the request already in the conversation).
- Valid acts, canonical order: `{order}`.
- Reorder the requested acts into canonical order regardless of how they were typed.
- Unknown token → report `unknown act "<x>" — valid: {order}` and continue with the rest. No valid act → print this usage and stop.

## 2. Run folder + intel (once, yourself — no dispatch)

1. `SLUG` = kebab-case of at most 4 task words (`run` if empty). `RUN=.claude/runs/$(date -u +%Y%m%dT%H%M)-$SLUG` under the repo root; `mkdir -p "$RUN"`. Make sure `.claude/runs/` is git-ignored (append it to `.gitignore` when missing).
2. Intel: jcodemunch `plan_turn` (query = TASK) + `assemble_task_context` on the impacted area; graphify `query_graph` only if `graphify-out/` exists; read `CODEX.md` and the root→target `CLAUDE.md` chain when present.
3. Write `$RUN/BRIEF.md`: task, surfaces (FE / BE / infra), impacted files, contracts at risk, acceptance criteria, open questions.
4. Write `$RUN/run.json`:
   `{{"task": TASK, "run": RUN, "started_utc": "<ISO-8601 UTC>", "start_sha": "<git rev-parse HEAD, or null>", "acts": [...], "done": [], "models": {{act: model}}, "expected_artifacts": {{}}}}`
   `/invoke-status`, the TeammateIdle gate and the suite gate read this file — keep it current.

Every specialist receives `$RUN/BRIEF.md` plus every artifact already in `$RUN/`; later acts start warm and never re-derive earlier context.

## 3. Dispatch — one specialist per act, canonical order

| act | agent | artifact (in `$RUN/`) | model (default) | mutates | checkpoint |
|-----|-------|-----------------------|-----------------|---------|------------|
{rows}

`model` is what opus-guard resolves by default: opus judges, sonnet executes. Execution agents escalate to opus when the prompt reports a failed previous attempt, or when it names no plan/spec artifact and the task is large. Do not pass `model=`; it would bypass that escalation. Pass it only when the user asked for a specific model.

For each act, in order:

1. Set `run.json.expected_artifacts["<agent>"] = "$RUN/<artifact>"` before dispatching.
2. `Agent(subagent_type="<agent>", description="<act>: <TASK>", prompt=...)`. The prompt names `$RUN/BRIEF.md`, each prior artifact path, and the exact output path `$RUN/<artifact>`; opus-guard adds the model and its `[label]`. Plain delegation: no `name=` (teams only for the mixed `impl` case below).
3. Wait for it, then append the act to `run.json.done`. Artifact missing or the act failed → re-dispatch once with the prompt prefixed `Previous attempt failed: <one-line reason>.` (this escalates execution agents to opus); still failing → stop and report.

Act-specific rules:

- **`impl`** [{impl_model}] surface-routes from the BRIEF: frontend → `frontend-implementor-specialist`; backend → `backend-implementor-specialist` (contract-first, publishes `IMPL-REPORT-BE.md ## CONTRACT`); mixed → spawn `team-lead` as a plain subagent (opus-pinned), which runs the BE↔FE team per `agents/team-lead.md` — set `expected_artifacts` for `IMPL-REPORT-BE.md`, `IMPL-REPORT-FE.md` and `INTEGRATION-REPORT.md`; user asked for no teams → sequential BE → FE → `integrator-specialist`; general / infra → `implementation-engineer`. A plan artifact in `$RUN/` satisfies `requires: plan`; without one the implementor writes a mini-plan first.
- **`design`** [{design_model}] — `frontend-uiux-designer`; every raster/video/3D/audio asset comes from Higgsfield (`higgsfield-generate`), never placeholders.
- **`clean`** edits code — treat REAP edits as real changes; the closers review them.
- **Checkpoints** (after {checkpoints}): interactive session → stop, show the artifact path + a 5-line summary, ask "continue with <remaining acts>?" and wait for the answer. Non-interactive (`-p`) → continue.
- **Security auto-add**: after the last mutating act, `git diff --name-only <start_sha>` (plus untracked files) matched against {globs} — any hit and `security` not requested → add `security` to the run before the closers.

## 4. Closers — only if an act that mutates ({mutating}) ran

Skip any closer whose act already ran explicitly in this run. Artifacts go to `$RUN/`.

{closer_block}

No mutating act → no closers; say so in one line.

## 5. Finish

Mark every act `done` in `run.json`, then report: `$RUN`, the artifact list, and the verdicts (Santa PASS / CHANGES REQUESTED, security PASS / BLOCK, QA PASS / FAIL). A BLOCK or FAIL is the headline, not a footnote.

## Fallback — Agent tool unavailable

Read `references/rosters.md` and run each act's skills yourself via the Skill tool, in canonical order. Never silently drop an act.

## Optional deterministic flow (explicit opt-in)

`~/.claude/workflows/invoke-fullstack.js` runs spec → plan → BE → FE → integrator → parallel(santa, security, docs) → qa as a Workflow script. Only the user starts it (`/invoke-fullstack`, or Workflow with `args: {{"task", "run", "slug"}}` after creating the run folder in step 2). Never launch it on the user's behalf.
"""


def render_rosters(acts: list[dict]) -> str:
    parts = [
        "# /invoke fallback rosters",
        "",
        BANNER,
        "",
        "Read ONLY when the Agent tool is unavailable. Invoke each act's skills via the Skill tool, in canonical order.",
        "",
    ]
    for a in acts:
        parts.append(f"## `{a['act']}` — {a['agent']} → `{a['artifact']}`")
        parts.append("")
        for s in a["local_skills"]:
            parts.append(f"- `{s}`")
        for s in a["superpowers_skills"]:
            parts.append(f"- `superpowers:{s}`")
        parts.append("")
    return "\n".join(parts)


def render_delegator(a: dict, policy: dict) -> str:
    model = act_model(a, policy)
    note = ACT_NOTES.get(a["act"], "")
    note = f"\n{note}\n" if note else ""
    description = (f"Run the {a['act'].upper()} act — forks straight into {a['agent']} ({model}); "
                   f"writes `{a['artifact']}` into the run folder. Single-act form of `/invoke {a['act']} -- <task>`.")
    fm = _frontmatter({
        "name": f"invoke-{a['act']}",
        "description": description,
        "argument-hint": "[task]",
        "context": "fork",
        "agent": a["agent"],
        "model": model,
    })
    return f"""{fm}
{BANNER}

Run the **{a['act']}** act for: $ARGUMENTS

You are `{a['agent']}`. Do your own intel first (jcodemunch `plan_turn` + `assemble_task_context`; graphify only if `graphify-out/` exists). Read `BRIEF.md` and any prior artifacts in the run folder when they exist.
{note}
Artifact: write `{a['artifact']}` into the newest `.claude/runs/*/` folder when one exists, otherwise create `{RUN_MKDIR}` (keep `.claude/runs/` git-ignored). Finish with the artifact path and a one-paragraph verdict.
"""


def render_utility(name: str) -> str:
    u = UTILITIES[name]
    fields = {"name": name, "description": u["description"]}
    fields.update(u["extra"])
    return f"""{_frontmatter(fields)}
{BANNER}

{u['body']}
"""


# ---------------------------------------------------------------------------
# emit / check
# ---------------------------------------------------------------------------

def render_all(cfg: dict, policy: dict) -> dict[Path, str]:
    acts = load_acts(cfg)
    out = {
        SKILLS_DIR / "invoke" / "SKILL.md": render_invoke(cfg, policy, acts),
        SKILLS_DIR / "invoke" / "references" / "rosters.md": render_rosters(acts),
    }
    for a in acts:
        out[SKILLS_DIR / f"invoke-{a['act']}" / "SKILL.md"] = render_delegator(a, policy)
    for name in UTILITIES:
        out[SKILLS_DIR / name / "SKILL.md"] = render_utility(name)
    return out


def _rel(p: Path) -> str:
    try:
        return str(p.relative_to(CLAUDE_DIR))
    except ValueError:
        return str(p)


def unexpected_dirs(expected: dict[Path, str]) -> list[Path]:
    want = {p.parent if p.name == "SKILL.md" else p.parent.parent for p in expected}
    have = {p for p in SKILLS_DIR.glob("invoke*") if p.is_dir()}
    return sorted(have - want)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="exit 1 if the skills on disk differ from the render")
    args = ap.parse_args()

    cfg = json.loads(CONFIG_PATH.read_text(encoding="utf-8"))
    policy = json.loads(MODEL_POLICY_PATH.read_text(encoding="utf-8")) if MODEL_POLICY_PATH.exists() else {}
    rendered = render_all(cfg, policy)
    stale = unexpected_dirs(rendered)

    if args.check:
        drift = []
        for path, content in rendered.items():
            if not path.is_file():
                drift.append(f"missing  {_rel(path)}")
            elif path.read_text(encoding="utf-8") != content:
                drift.append(f"stale    {_rel(path)}")
        drift += [f"unexpected {_rel(p)}/ (not generated from config)" for p in stale]
        if drift:
            print("gen-invoke-skills --check: DRIFT\n  " + "\n  ".join(drift))
            print("run `python3 ~/.claude/hooks/gen-invoke-skills.py` and delete unexpected dirs.")
            return 1
        print(f"gen-invoke-skills --check: OK ({len(rendered)} files in sync)")
        return 0

    for path, content in rendered.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")
    print(f"gen-invoke-skills: wrote {len(rendered)} files under {_rel(SKILLS_DIR)}/")
    for p in stale:
        print(f"  warning: unexpected {_rel(p)}/ is not generated from config - delete it")
    return 0


if __name__ == "__main__":
    sys.exit(main())
