#!/usr/bin/env python3
"""
Smart Skill Router — selects exactly 3 ranked skills for the current file write.

Public API:
    select_skills(file_path, surface, is_first_write=False) -> list[dict]

Each dict:
    {
        "name": "skill-name",
        "path": "/home/.../.claude/skills/<name>/SKILL.md",
        "priority": "MUST-READ" | "SHOULD-READ" | "REFERENCE",
    }

Cross-cutting extras (not counted in the 3) are appended with priority "CROSS-CUT".
"""
from __future__ import annotations

import json
import os
from pathlib import Path

_HOOK_DIR = Path(__file__).resolve().parent
_CONFIG_PATH = _HOOK_DIR / "skill_router.config.json"
_SKILL_ROOT = Path.home() / ".claude" / "skills"
WEIGHTS_FILE = _HOOK_DIR / "skill_router_weights.json"


def _load_weights() -> dict[str, float]:
    """Load skill weights from skill_router_weights.json if present.

    Returns a dict mapping skill slug -> float weight (default 1.0 if absent).
    Weights are generated by skill-router-weight-updater.py from telemetry.
    """
    if not WEIGHTS_FILE.is_file():
        return {}
    try:
        data = json.loads(WEIGHTS_FILE.read_text(encoding="utf-8"))
        weights = data.get("weights", {})
        # Validate: weights must be floats in [0.1, 2.0]
        return {
            k: float(max(0.1, min(2.0, v)))
            for k, v in weights.items()
            if isinstance(k, str) and isinstance(v, (int, float))
        }
    except (json.JSONDecodeError, OSError, ValueError):
        return {}


_SKILL_WEIGHTS: dict[str, float] = _load_weights()

# ---------------------------------------------------------------------------
# Built-in rules (fallback when config absent or partially missing)
# ---------------------------------------------------------------------------

_BUILTIN_FRONTEND_RULES: list[dict] = [
    {
        "id": "fe_api",
        "match": {"path_contains_any": ["/api/", "/api-client", "api.ts", "api.js"]},
        "skills": ["frontend-response-handling", "frontend-api-standards", "frontend-server-data-patterns"],
    },
    {
        "id": "fe_hooks",
        "match": {
            "path_contains_any": ["/src/hooks/", "/hooks/use", "use-", ".hook."],
            "exclude_paths": [".claude/hooks", "/.claude/hooks"],
        },
        "skills": ["react-hooks-patterns", "frontend-server-data-patterns", "frontend-standards-always-follow"],
    },
    {
        "id": "fe_store_redux",
        "match": {"path_contains_any": ["/store/", "slice.", "reducer.", "redux", "selector."]},
        "skills": ["frontend-standards-always-follow", "frontend-structure-standards", "react-hooks-patterns"],
    },
    {
        "id": "fe_routes",
        "match": {"path_contains_any": ["/routes/", "/router/", "route.tsx", "route.ts", "routes.ts"]},
        "skills": ["frontend-standards-always-follow", "frontend-structure-standards", "scaffold-standards"],
    },
    {
        "id": "fe_test",
        "match": {"path_contains_any": [".test.", ".spec.", "__tests__", "_test.ts", "_test.tsx"]},
        "skills": ["webapp-testing", "tdd", "frontend-standards-always-follow"],
    },
    {
        "id": "fe_auth",
        "match": {"path_contains_any": ["/auth/", "/login/", "/guard/", "protected", "session"]},
        "skills": ["security-and-hardening", "frontend-standards-always-follow", "frontend-response-handling"],
    },
    {
        "id": "fe_vite_config",
        "match": {"filename_contains_any": ["vite", "tsconfig", "eslint", "postcss", "tailwind.config"]},
        "skills": ["vite-react-best-practices", "frontend-standards-always-follow", "frontend-structure-standards"],
    },
    {
        "id": "fe_ui_design",
        "match": {"path_contains_any": ["/components/", "/layout/", "/pages/", "/views/"]},
        "skills": ["impeccable", "huashu-design", "ui-ux-pro-max", "taste-skill", "frontend-ui-engineering", "design-extract"],
    },
    {
        "id": "fe_component_tsx",
        "match": {"extensions": [".tsx", ".jsx"]},
        "skills": ["frontend-standards-always-follow", "react-hooks-patterns", "tailwind-design-system"],
    },
    {
        "id": "fe_default",
        "match": {"catch_all": True},
        "skills": ["frontend-standards-always-follow", "frontend-structure-standards", "react-hooks-patterns"],
    },
]

_BUILTIN_BACKEND_RULES: list[dict] = [
    {
        "id": "be_cursor_infra",
        "match": {
            "path_contains_any": [".claude/hooks/", ".claude/rules/", ".claude/hooks/"],
        },
        "skills": ["tool-and-doc-selection", "dead-code-and-change-audit", "debug-investigation"],
    },
    {
        "id": "be_go_test",
        "match": {"filename_contains_any": ["_test.go"]},
        "skills": ["golang-testing", "tdd", "backend-standards-always-follow"],
    },
    {
        "id": "be_controller",
        "match": {"filename_contains_any": ["controller", ".controller."]},
        "skills": ["backend-standards-always-follow", "backend-api-standards", "service-layer-standards"],
    },
    {
        "id": "be_service",
        "match": {"filename_contains_any": ["service", ".service."]},
        "skills": ["service-layer-standards", "backend-standards-always-follow", "backend-error-handling"],
    },
    {
        "id": "be_schema",
        "match": {"filename_contains_any": ["schema", ".schema."]},
        "skills": ["backend-standards-always-follow", "backend-api-standards", "scaffold-standards"],
    },
    {
        "id": "be_model",
        "match": {"filename_contains_any": ["model", ".model."]},
        "skills": ["backend-standards-always-follow", "domain-scaffold-patterns", "service-layer-standards"],
    },
    {
        "id": "be_route",
        "match": {"filename_contains_any": ["route", "router", ".route."]},
        "skills": ["backend-standards-always-follow", "backend-api-standards", "scaffold-standards"],
    },
    {
        "id": "be_test",
        "match": {"filename_contains_any": [".test.", ".spec.", "_test.ts"]},
        "skills": ["tdd", "backend-standards-always-follow", "backend-performance-standards"],
    },
    {
        "id": "be_middleware",
        "match": {"filename_contains_any": ["middleware", "auth", "guard", "session"]},
        "skills": ["security-and-hardening", "backend-standards-always-follow", "backend-error-handling"],
    },
    {
        "id": "be_migration",
        "match": {"filename_contains_any": ["migration", "migrate", ".sql"]},
        "skills": ["postgres-patterns", "backend-standards-always-follow", "deprecation-and-migration"],
    },
    {
        "id": "be_contract",
        "match": {"filename_contains_any": ["contract", "response", "envelope"]},
        "skills": ["api-contract-standards", "backend-api-standards", "backend-standards-always-follow"],
    },
    {
        "id": "be_security_audit",
        "match": {"filename_contains_any": ["security", "audit", "owasp"]},
        "skills": ["cso", "owasp-security", "security-and-hardening"],
    },
    {
        "id": "be_go_file",
        "match": {"extensions": [".go"]},
        "skills": ["golang-patterns", "backend-standards-always-follow", "service-layer-standards"],
    },
    {
        "id": "be_default",
        "match": {"catch_all": True},
        "skills": ["backend-standards-always-follow", "service-layer-standards", "backend-api-standards"],
    },
]

_BUILTIN_CROSS_CUTTING = {
    "always": ["dead-code-and-change-audit"],
    "first_write_only": ["architect-system-design", "codebase-start-point-guide"],
    "verification": ["verification-loop"],
    "debug": ["doubt-driven-development", "debug-investigation"],
    "implementation": ["source-driven-development", "doubt-driven-development"],
}

_PRIORITY_LABELS = ["MUST-READ", "SHOULD-READ", "REFERENCE"]


# ---------------------------------------------------------------------------
# Config loader
# ---------------------------------------------------------------------------

def _load_config() -> dict:
    if not _CONFIG_PATH.is_file():
        return {}
    try:
        return json.loads(_CONFIG_PATH.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return {}


# ---------------------------------------------------------------------------
# Matching helpers
# ---------------------------------------------------------------------------

def _norm(s: str) -> str:
    return s.replace("\\", "/").lower()


def _matches_rule(file_path: str, rule: dict) -> bool:
    """Return True if the file_path satisfies the match spec in the rule."""
    match = rule.get("match", {})
    fp_norm = _norm(file_path)
    filename = _norm(Path(file_path).name)
    ext = Path(file_path).suffix.lower()

    for pattern in match.get("exclude_paths", []):
        if _norm(pattern) in fp_norm:
            return False

    # catch_all always matches (used as the last fallback)
    if match.get("catch_all"):
        return True

    matched = False

    # path_contains_any — checked against the full normalised path
    for pattern in match.get("path_contains_any", []):
        if _norm(pattern) in fp_norm:
            matched = True
            break

    # filename_contains_any — checked against the filename only
    if not matched:
        for pattern in match.get("filename_contains_any", []):
            if _norm(pattern) in filename:
                matched = True
                break

    # extensions — exact suffix match
    if not matched:
        for ext_pat in match.get("extensions", []):
            if ext == ext_pat.lower():
                matched = True
                break

    return matched


# ---------------------------------------------------------------------------
# Core selection
# ---------------------------------------------------------------------------

def _skill_path(name: str) -> str:
    return str((_SKILL_ROOT / name / "SKILL.md").resolve())


def _build_entry(name: str, priority: str) -> dict:
    return {"name": name, "path": _skill_path(name), "priority": priority}


def select_skills(
    file_path: str,
    surface: str,
    is_first_write: bool = False,
    cross_cut_mode: str | None = None,
) -> list[dict]:
    """
    Returns a list of skill dicts ranked by relevance.

    Always returns exactly 3 items with priorities MUST-READ / SHOULD-READ / REFERENCE,
    followed by cross-cutting entries (priority CROSS-CUT) for dead-code-and-change-audit
    and (on first write) architect-system-design.

    Parameters
    ----------
    file_path : str
        The absolute or relative path being written to.
    surface : str
        One of "frontend", "backend", or "fullstack".
    is_first_write : bool
        True when this is the first qualifying write in the conversation (controls
        whether architect-system-design cross-cut is included).
    """
    cfg = _load_config()

    surface_lower = (surface or "").strip().lower()

    # For fullstack, default to frontend rules for the primary 3; the caller can
    # call twice (once per surface) or rely on the fullstack path in the hook.
    if surface_lower in ("frontend", "fullstack"):
        rules = cfg.get("frontend_rules") or _BUILTIN_FRONTEND_RULES
    else:
        rules = cfg.get("backend_rules") or _BUILTIN_BACKEND_RULES

    max_by_rule = cfg.get("max_primary_skills_by_rule") or {}
    default_max = int(cfg.get("max_primary_skills", 3))

    matched_rule_id = ""
    matched_skills: list[str] = []
    for rule in rules:
        if _matches_rule(file_path, rule):
            matched_rule_id = str(rule.get("id") or "")
            cap = int(max_by_rule.get(matched_rule_id, default_max))
            matched_skills = list(rule.get("skills", [])[: max(1, cap)])
            break

    while len(matched_skills) < min(default_max, 3):
        matched_skills.append(
            "frontend-standards-always-follow" if surface_lower in ("frontend", "fullstack") else "backend-standards-always-follow"
        )

    # Sort by (weight × score) descending, return top N
    # Weight comes from skill_router_weights.json if present (default 1.0)
    # Score is derived from position in the rule's skill list (first = highest score)
    _position_scores = {skill: 1.0 / (i + 1) for i, skill in enumerate(matched_skills)}
    matched_skills.sort(
        key=lambda skill: _SKILL_WEIGHTS.get(skill, 1.0) * _position_scores.get(skill, 0.5),
        reverse=True,
    )

    priority_labels: list[str] = cfg.get("priority_labels") or _PRIORITY_LABELS
    primary_count = len(matched_skills)
    result: list[dict] = [
        _build_entry(
            matched_skills[i],
            priority_labels[i] if i < len(priority_labels) else "REFERENCE",
        )
        for i in range(primary_count)
    ]

    # Cross-cutting additions
    cross = cfg.get("cross_cutting") or _BUILTIN_CROSS_CUTTING
    for name in cross.get("always", []):
        result.append(_build_entry(name, "CROSS-CUT"))
    if is_first_write:
        for name in cross.get("first_write_only", []):
            result.append(_build_entry(name, "CROSS-CUT"))
    if cross_cut_mode:
        for name in cross.get(cross_cut_mode, []):
            entry = _build_entry(name, "CROSS-CUT")
            if entry not in result:
                result.append(entry)

    return result


# ---------------------------------------------------------------------------
# Compact formatter (used by fullstack-skills-reminder.py)
# ---------------------------------------------------------------------------

def format_compact(
    file_path: str,
    surface: str,
    skills: list[dict],
) -> str:
    """
    Renders the ~300-char compact format expected by the hook.

    Example output (frontend component):
        [MANDATORY] Frontend write detected: MyComponent.tsx
        READ NOW: `~/.claude/skills/frontend-standards-always-follow/SKILL.md`
        ALSO: `react-hooks-patterns`, `tailwind-design-system`
        Cross-cut: dead-code-and-change-audit, architect-system-design
        Full checklist: ~/.claude/rules/mandatory-skill-protocol.mdc
    """
    filename = Path(file_path).name or file_path
    surface_label = surface.capitalize()

    primary = [s for s in skills if s["priority"] not in ("CROSS-CUT",)]
    cross = [s for s in skills if s["priority"] == "CROSS-CUT"]

    must = primary[0] if primary else None
    also = primary[1:3]

    # Shorten the MUST-READ path to the tilde form for readability
    must_path = must["path"] if must else ""
    home = str(Path.home())
    must_path_short = must_path.replace(home, "~") if must_path.startswith(home) else must_path

    also_names = ", ".join(f"`{s['name']}`" for s in also) if also else ""
    cross_names = ", ".join(s["name"] for s in cross) if cross else ""

    lines = [
        f"[MANDATORY] {surface_label} write detected: {filename}",
        f"READ NOW: `{must_path_short}`",
    ]
    if also_names:
        lines.append(f"ALSO: {also_names}")
    if cross_names:
        lines.append(f"Cross-cut: {cross_names}")
    lines.append("Full checklist: ~/.claude/rules/mandatory-skill-protocol.mdc")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# CLI test shim
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import sys

    path = sys.argv[1] if len(sys.argv) > 1 else "src/components/MyWidget.tsx"
    surf = sys.argv[2] if len(sys.argv) > 2 else "frontend"
    first = (sys.argv[3] if len(sys.argv) > 3 else "0") == "1"

    skills = select_skills(path, surf, is_first_write=first)
    print(format_compact(path, surf, skills))
    print()
    print(json.dumps(skills, indent=2))
